# Generated by Django 4.2.16 on 2026-07-06 20:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(help_text='The pipeline being executed.', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pipelines.pipeline')),
            ],
            options={
                'verbose_name': 'Pipeline Execution',
                'verbose_name_plural': 'Pipeline Executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, help_text='Actual duration in seconds.', null=True)),
                ('execution', models.ForeignKey(help_text='The parent pipeline execution.', on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='executions.pipelineexecution')),
                ('task', models.ForeignKey(help_text='The specific task being executed.', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pipelines.pipelinetask')),
            ],
            options={
                'verbose_name': 'Task Execution',
                'verbose_name_plural': 'Task Executions',
                'ordering': ['execution', 'started_at'],
                'indexes': [models.Index(fields=['status'], name='executions__status_2aba10_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='taskexecution',
            constraint=models.UniqueConstraint(fields=('execution', 'task'), name='unique_task_per_execution'),
        ),
        migrations.AddIndex(
            model_name='pipelineexecution',
            index=models.Index(fields=['status'], name='executions__status_3713f4_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelineexecution',
            index=models.Index(fields=['created_at'], name='executions__created_e8ba4f_idx'),
        ),
    ]
