# Generated by Django 4.2.16 on 2026-07-06 20:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated duration in seconds.')),
                ('failure_probability', models.FloatField(default=0.0, help_text='Probability of simulated failure (0.0 to 1.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Optional ordering for UI display.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(help_text='The pipeline this task belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pipelines.pipeline')),
            ],
            options={
                'verbose_name': 'Pipeline Task',
                'verbose_name_plural': 'Pipeline Tasks',
                'ordering': ['pipeline', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depends_on', models.ForeignKey(help_text='The task that must complete first.', on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='pipelines.pipelinetask')),
                ('task', models.ForeignKey(help_text='The task that is blocked/waiting.', on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='pipelines.pipelinetask')),
            ],
            options={
                'verbose_name': 'Task Dependency',
                'verbose_name_plural': 'Task Dependencies',
            },
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'depends_on'), name='unique_task_dependency'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.CheckConstraint(check=models.Q(('task', models.F('depends_on')), _negated=True), name='prevent_self_dependency'),
        ),
    ]
